### ISSUE TITLE
you need to dowload the last update and run your xbox app on the PC, then click on grab Xauth and grab info.

### ISSUE THREAD

**Issue by xccis** [ItsLogic/Xbox-Achievement-Unlocker#10]
you need to dowload the last update and run your xbox app on the PC, then click on grab Xauth and grab info.
And now you can unlock the achievements you need ^^

how do i find it

**Comment by ItsLogic** [comment]
stop making issues. Reply to the person actually talking to you instead of making a new issue to ask another question
