### ISSUE TITLE
[Game]: Grand Theft Auto V (Xbox One)

### ISSUE THREAD

**Issue by Dragonfyre08** [ItsLogic/Xbox-Achievement-Unlocker#126]
### Confirmation

- [X] I have verified that this is not a duplicate request.

### Game Link

https://www.trueachievements.com/game/Grand-Theft-Auto-V-Xbox-One/achievements

### Game Platform

Console only

### Additional Game Information

All achievements

**Comment by ItsLogic** [comment]
dupe of #106
