### ISSUE TITLE
Unable to find TitleID's

### ISSUE THREAD

**Issue by DarkUnicycle** [ItsLogic/Xbox-Achievement-Unlocker#14]
I probably already know the answer to this question, but I wanted to ask how I would locate Title IDs as I'm unable to locate much info online.

**Comment by ItsLogic** [comment]
I do plan to create an easily accessible list in the future but it will take quite a bit of time so for now you will need to grab it through network traffic yourself.
Opening the game page you want in either the Xbox app or Xbox console companion app should be enough to get the Title ID to show up inside an app like fiddler. The URL for the request will most likely contain "titlehub" or similar

**Comment by DarkUnicycle** [comment]
Gotcha, I attempted to find the Title ID or anything similar, but it seems I'm having a hard time locating the info. I'll continue to attempt on my side but I thank you for adding the feature in the future to make things more user friendly.

**Comment by SilverWhale44** [comment]
If you end up finding a method to do so please report back. I'm trying to figure out the same and will share any progress if I figure something out.

**Comment by DarkUnicycle** [comment]
Will do, I figured they would include the Title ID in the URL but that didn't work out and it seems when I use any Xbox App the app isn't able to bring up any title as Xbox Auth kicked back Fiddler.

**Comment by DarkUnicycle** [comment]
After some testing, I was able to find out how to locate the Title ID however it doesn't seem to be for the title I'm viewing. I was able to pull two separate games from one search within fiddler, but I'll continue my search until I get a pattern.

**Comment by HaZheRMx** [comment]
you can see the TITLEID via Xbox One. in "Manage game and add-ons" then "File information"

**Comment by DarkUnicycle** [comment]
Thank you, we were trying to find it on PC only but the key was on the console.

**Comment by DarkUnicycle** [comment]
It looks like our quest continues, the TitleID might be different as the games that I've tried aren't working

**Comment by ItsLogic** [comment]
I will record a short video today

**Comment by DarkUnicycle** [comment]
I was able to find the titlehub with the games that you've recently played within list but I'm noticing there's TitleIDs that I haven't played before but I'll post the list of IDs once I've gathered everything if you guys would like

**Comment by DarkUnicycle** [comment]
[TitleIDs.txt](https://github.com/ItsLogic/Xbox-Achievement-Unlocker/files/9439954/TitleIDs.txt)

Here's what I was able to find for right now, however I've noticed that some of these are just games that've I've played in general and not in the Xbox Platform such as Steam. So make sure to search to make sure you can obtain progress before using them

**Comment by DarkUnicycle** [comment]
> I will record a short video today

Let me know if you want me to send you these via a different platform or just complete the full list that I have. I don't mind helping out in anyway when I can

**Comment by ItsLogic** [comment]
The video is currently uploading. 

> Let me know if you want me to send you these via a different platform or just complete the full list that I have. I don't mind helping out in anyway when I can

I plan to make a seperate github repo with just a CSV of a bunch of title IDs that anyone can make a pull request to so it will be mostly user sourced as it will be a huge list
Ill make it later today and throw in a few example title IDs so that people know the format before adding to it

**Comment by ItsLogic** [comment]
Here is the video: https://www.youtube.com/watch?v=SjRgunRSm8s
This only works for games you can view in either the new xbox app or console companion app weither that is through a search, a friends recently played or your own profile. 

Any games outside of that you can send a HTTPS post to this URL with the product id which you can find in the url from just opening the app on the web version of the xbox store
![image](https://user-images.githubusercontent.com/38233332/187086796-fcfc6a7f-bc66-449a-af61-1166e1e00e04.png)

**Comment by SilverWhale44** [comment]
Thanks for all the information above. After finding a way to confirm title IDs I sought out an easier method of acquisition. We will be using the xboxdvr website for assistance. 

https://www1.xboxdvr.com/games/vampyr/videos - Go to any game's video page, using Vampyr as an example. 

Right Click > View Page Source. CTRL+F and search "window.current"

You should see something like "window.current_game = '449394673';" 

"449394673" is the Title ID. 

I'll be adding more to the note pad provided above as I find more. Would be happy to contribute to a CSV.

**Comment by DarkUnicycle** [comment]
> Thanks for all the information above. After finding a way to confirm title IDs I sought out an easier method of acquisition. We will be using the xboxdvr website for assistance.
> 
> https://www1.xboxdvr.com/games/vampyr/videos - Go to any game's video page, using Vampyr as an example.
> 
> Right Click > View Page Source. CTRL+F and search "window.current"
> 
> You should see something like "window.current_game = '449394673';"
> 
> "449394673" is the Title ID.
> 
> I'll be adding more to the note pad provided above as I find more. Would be happy to contribute to a CSV.

You're a genius. Once I get home I can start double checking the progress I've made with the list I posted above and continue to add to that.

**Comment by SilverWhale44** [comment]
Close to 20 titles now and so far so good. 

With some games like Call to Sea you will see two versions of the game on the site, it doesn't indicate it but one is for the windows and one is for console. Unless the game includes (windows) in the name to differentiate this it can be hard to tell which is which. 

Worth noting, maybe someone will figure out a way to tell without manually checking by adding both  games to their history and verifying.

**Comment by ItsLogic** [comment]
The repo is now created. Feel free to make your pull requests to add to the list
https://github.com/ItsLogic/Xbox-TitleIDs

**Comment by ItsLogic** [comment]
> Close to 20 titles now and so far so good.
> 
> With some games like Call to Sea you will see two versions of the game on the site, it doesn't indicate it but one is for the windows and one is for console. Unless the game includes (windows) in the name to differentiate this it can be hard to tell which is which.
> 
> Worth noting, maybe someone will figure out a way to tell without manually checking by adding both games to their history and verifying.

I dont think there is an easy way to check using the xboxdvr site. Using my Product ID method its easy since you actually need to visit the store page but you can supply multiple product IDs at once so you might be able to grab them faster 
![image](https://user-images.githubusercontent.com/38233332/187089408-4bd872ab-83f0-4052-b079-2d5ea5b51d40.png)

**Comment by DarkUnicycle** [comment]
Just posted my TitleID update on the other post, since there's quite a few of us working on this now would we want to make a discord to better have a field of communication?

**Comment by ItsLogic** [comment]
Im not opposed to one. It certainly would make it easier to share ideas and data. I could make a server for this tool in general and make a channel or something for this topic? Would help with people who dont understand how it works too
Unless you were just planning on making a groupchat im fine with either

**Comment by DarkUnicycle** [comment]
Yeah, I'm down for a discord group. Mine is DarkUnicycle#6541

**Comment by ItsLogic** [comment]
Well here we go https://discord.gg/ugDvSw7cns

**Comment by thevenomsnake** [comment]
https://xboxdb.altervista.org/browse/f

**Comment by mickygamer44** [comment]
I still don't understand how to find a title ID with the source code of the page on the xbox store

**Comment by ItsLogic** [comment]
closing this as there is now game search fuctionality added in 2.1.0

**Comment by mrbeardad** [comment]
I think I've found a new way to get the title id.

<img width="3840" height="2076" alt="Image" src="https://github.com/user-attachments/assets/60423c82-be15-4ef1-bb09-78454e2a0983" />
