### ISSUE TITLE
Xbox 360 games and Homebrew apps are throwing an exception

### ISSUE THREAD

**Issue by NullP01nterExcept10n** [ItsLogic/Xbox-Achievement-Unlocker#16]
I bet it's hard or nearly impossible to add support for 360 games since its achievements system differs from what modern Xbox is using.

Can you at least show a proper message that X360 titles aren't supported so that people won't quit the app accidentally thinking that it has been broken? I mean, would be cool if it's still possible to add the support of X360 titles, but if you're sure it isn't possible ["-why isn't it possible? -it's just not. -why not you<...>"] then at least show the message that 360 titles aren't supported by the tool.

The same goes for the apps like homebrew (such as Retroarch emulator), which aren't having any achievements at all. The homebrew case is a bit obvious that you just shouldn't touch what obviously won't work, but hey, let's make your tool somewhat dumb-proof.

**Comment by ItsLogic** [comment]
Honestly the only reason 360 games are included in the list is because I didnt have any on my recents so I didnt know how to filter them out. I plan to completely remove them from the next release
As for 0 achivement games I forgot to add error checking so ill fix that at some point too

**Comment by ItsLogic** [comment]
360 games have been removed from the list. I have added a check for 0 achievement games so it shouldnt throw an error anymore
