### ISSUE TITLE
[Bug]: Page display refresh

### ISSUE THREAD

**Issue by RainbowFurry** [ItsLogic/Xbox-Achievement-Unlocker#170]
### What version of the Xbox Achievement Unlocker were you using (you can see this in the settings page)?

1.3.5

### Tool Section

Home

### What is the bug?

![Bild_2024-05-02_131614610](https://github.com/Fumo-Unlockers/Xbox-Achievement-Unlocker/assets/168726441/480c5c2d-cf63-47c1-8636-4a5601e1fb2e)
When I switch from page 1 to 2, nothing happens the first time. Only the second time I switch everything is updated.

(The Version is not like in the Bug Report page in the Settings. It is in the Info View)
![image](https://github.com/Fumo-Unlockers/Xbox-Achievement-Unlocker/assets/168726441/4e42b119-a1a8-415c-b886-2982d6413b15)

**Comment by ItsLogic** [comment]
I won't fix this. Just wait until the profile info has fully loaded before changing pages.
