### ISSUE TITLE
[Bug]: Settings not updated

### ISSUE THREAD

**Issue by RainbowFurry** [ItsLogic/Xbox-Achievement-Unlocker#171]
### What version of the Xbox Achievement Unlocker were you using (you can see this in the settings page)?

1.3.5

### Tool Section

Settings

### What is the bug?

If i Update the Settings i need to restart the App. Otherwise no settings changes will work.

**Comment by ItsLogic** [comment]
Yeah this is my bad I never actually reload the settings after setting them 💀 
I'll fix it when I get back

**Comment by ItsLogic** [comment]
settings are now updated properly after being set
