### ISSUE TITLE
agradeçimento[Enhancement]: 

### ISSUE THREAD

**Issue by hello72823** [ItsLogic/Xbox-Achievement-Unlocker#177]
### Request Selection

New Feature

### What is your request?

ola bom dia peço desculpas por pedir assis mais poderia tentar fazer dos jogos gta v, state of decay, assasins creed black flag os call of duty teria como lembrando peço desculpas por ser tão incoveniene espero que conciga ler essa mensagen pois sou um grande fan e agradeço por fazer esse app vc e muito bom quem manda essa mensagem @hackbrasil@

**Comment by ItsLogic** [comment]
Invalid issue
