### ISSUE TITLE
What's the point of this if it gets you banned?

### ISSUE THREAD

**Issue by KitCat36** [ItsLogic/Xbox-Achievement-Unlocker#18]
First thanks for this program, but I have a legit question, what's the point of this program/tool if it can get you banned? I saw the other thread where someone said they were banned and you said it's against Xbox's terms of service and you can't do anything about it.
so I wanted to know what's the goal behind this project? to unlock Xbox achievements on dummy/alt Xbox accounts just for fun? or people use it on their main Xbox account and get banned?

is there something you can do/change to make it ban proof?

**Comment by Deadlyspy** [comment]
I didn't use it wisely. I did over 20,000 points and some online halo achievements in one sitting. If used over time it should be harder to track.

**Comment by Deadlyspy** [comment]
Just once.

**Comment by ItsLogic** [comment]
I'm just making it for coding and RE practice not gonna lie. I don't even use it. As for the ban risk idk. I know you can get banned but idk what the triggers are. All I know is that In my testing I haven't hit them since I haven't been banned yet.


I can't change anything. I unlock the achievements the same way the games do

Gonna close this since it isn't actually an issue but you can still talk here if you want

**Comment by PKXLIVE** [comment]
I would just play the game normally and use it to clean up any
achievements missed. Its probably not the best Idea to use it for online
multiplayer achivments

**Comment by ItsLogic** [comment]
> > I'm just making it for coding and RE practice not gonna lie. I don't even use it. As for the ban risk idk. I know you can get banned but idk what the triggers are. All I know is that In my testing I haven't hit them since I haven't been banned yet.
> > 
> > I can't change anything. I unlock the achievements the same way the games do
> > 
> > Gonna close this since it isn't actually an issue but you can still talk here if you want
> 
> 
> so there is no way Xbox can know a single achievement is unlocked legit or using this tool?

Not sure what data they collect when achievements are unlocked but they probably could tell if they wanted to? I know I could tell the difference between my request and a legitimate one. 

Whether they do or not... Who knows

**Comment by agoodideaihas** [comment]
An account unlocking 20000g in a day + halo online achievements (that are probably linked to online stats) would probably raise some kind of automatic flag to investigate an account and ban it. The real question is if this tool can be used to clean up stray achievements like coop of games that have no one playing or too grindy without it being problematic and getting a ban. I've been using it to clean strays and I've have no problem but I always am executing the game of the achievement I want to pop up in the background.
