### ISSUE TITLE
"Unlock All Achievements" issue

### ISSUE THREAD

**Issue by thevenomsnake** [ItsLogic/Xbox-Achievement-Unlocker#19]
I tried all three games and all achievements were unlocked in "[Xbox-Achievement-Unlocker]"'s list. But the official Xbox app doesn't show all achievements. The most confusing thing is that the filter unlocked achievements item is empty.

https://imgur.com/Y7GDb5b

GAME LIST:
FINAL FANTASY VIII Remastered
FINAL FANTASY IX
Far Cry® New Dawn

**Comment by HaZheRMx** [comment]
just wait... trash Xbox servers

**Comment by ItsLogic** [comment]
Yeah this is just a delay with xbox servers when you unlock a bunch at once. They will show in a few days
