### ISSUE TITLE
Achivements not all showing up in game stats (maybe xbox app bug)

### ISSUE THREAD

**Issue by meow-0** [ItsLogic/Xbox-Achievement-Unlocker#20]
I wanted to test this on a random game. I selected farming sim 22 and unlocked all. This is what my achivement progress looks like 
![image](https://user-images.githubusercontent.com/67144339/201477027-6c6d4f2a-c17d-4d8b-8c49-b97dc83991b6.png)

However if i sort for achivements locked on the game, there is no locked achivements:
![image](https://user-images.githubusercontent.com/67144339/201477089-213d7b1a-8475-463a-9773-1543b66cac37.png)

Im unsure if this is just the Xbox app for windows thats shit or if its the program

**Comment by ItsLogic** [comment]
See issue #19
It will fix itself eventually the Xbox app just bugs when you unlock a bunch of achievements. If they are all ticked in the unlocker and have an unlock date then it will show as completed in a few hours/days

**Comment by meow-0** [comment]
Everything seems to have an unlock date. Must have missed #19.
I just got confused since it was showing on has having all achivements on xbox gamebar yet the xbox app didnt have all of them.
