### ISSUE TITLE
[Game]:  Resident Evil 7: Biohazard Grotesque Ver.

### ISSUE THREAD

**Issue by GooseyGames** [ItsLogic/Xbox-Achievement-Unlocker#228]
### Confirmation

- [X] I have verified that this is not a duplicate request.

### Game Link

https://www.trueachievements.com/game/Resident-Evil-7-Grotesque/achievements?gamerid=1493252

### Game Platform

Console and PC

### Additional Game Information

The Japanese stack of Resident Evil 7 which has a separate achievement stack but is also E.B. Would be great if someone knows how to make work.

**Comment by NextLVLHasH** [comment]
@ItsLogic close this its already completed
:D

**Comment by ItsLogic** [comment]
oopsie
