### ISSUE TITLE
[Suggestions] UI/UX Suggestions & Questions

### ISSUE THREAD

**Issue by GMatrixGames** [ItsLogic/Xbox-Achievement-Unlocker#23]
Hi, came across this while I was looking for easy games to get achievements on, and this made it a whole lot easier lol.

Some suggestions:
- Search bar for games/title IDs.
- Gray out or have a way to filter games that are 100% complete already.
- Until event-based achievements are implemented, having a filter to remove those would be a nice qol change too.

Some questions:
- Will there be a way to use this on Xbox 360 games at all? I would assume it's **similar**, but I haven't done any research in this space, so I am probably talking out of my ass.
- I had seen that you had some progress on event-based achievements. Is there any way I could help with that? (Or do you pretty much have what you need to do down)

**Comment by ItsLogic** [comment]
>Search bar for games/title IDs.

This is planned but it currently seems non trivial. I plan to start working on it after the UI redesign and have a few ideas on how I could implement it

>Gray out or have a way to filter games that are 100% complete already.
Until event-based achievements are implemented, having a filter to remove those would be a nice qol change too.

Im pretty sure I would be able to filter out completed games (ill need to double check what is returned in the API but completion state should be there) I cant feasibly filter event based games though as I would need to load the whole achievements list to figure out if it was event based or not.

>Will there be a way to use this on Xbox 360 games at all? I would assume it's similar, but I haven't done any research in this space, so I am probably talking out of my ass.

Nope. Use Horizon instead I dont plan to support anything other than xbox one/series/xbox pc achievements

>I had seen that you had some progress on event-based achievements. Is there any way I could help with that? (Or do you pretty much have what you need to do down)

A HTTPS capture of whatever goes on when completing an event based achievement would be really helpful but thats about it

**Comment by GMatrixGames** [comment]
> Nope. Use Horizon instead I dont plan to support anything other than xbox one/series/xbox pc achievements
So you suggest to use a PAID piece of software as an alternative?

> A HTTPS capture of whatever goes on when completing an event based achievement would be really helpful but thats about it
I'll see if I can help with that, as long as the default fiddler config works with it.

**Comment by GMatrixGames** [comment]
> You can use Velocity! It's free to use.

Does that work on an Xbox One with a 360 game on it, or does it require the 360 hardware?

**Comment by GMatrixGames** [comment]
@ItsLogic You mentioned just an HTTPs capture would be good. There's no way to get a proper capture of any game as it fails to sign-in.

Is there a url exclusion I need or smth?

**Comment by hentei009** [comment]
> Nope. Use Horizon instead I dont plan to support anything other than xbox one/series/xbox pc achievements

Please add support for Windows 8/8.1 games.
No matter how hard I try to start this game, in windows 10/11 it just doesn't start.
![Captura de pantalla (23)](https://user-images.githubusercontent.com/39165912/215339558-c35c7dfd-3ba0-43b0-9e60-c5be54761071.png)
P.S. I bought this game and even though I already tried with Windows 8 ISO, the store simply crashes and won't let me install it, even with the APPX installer
