### ISSUE TITLE
Is this bannable??

### ISSUE THREAD

**Issue by wobblerr** [ItsLogic/Xbox-Achievement-Unlocker#25]
I've been paying for a service that does that and they told me to be careful as I may get banned.

**Comment by bournejason** [comment]
yes

**Comment by wobbleris** [comment]
alr ty

**Comment by HaZheRMx** [comment]
this is the same as insulting in an Xbox group: they will ban you.

Simply: DO NOT ABUSE!

**Comment by AlexandreCA** [comment]
> I've been paying for a service that does that and they told me to be careful as I may get banned.

no!

**Comment by ItsLogic** [comment]
As mentioned above yes it is bannable. You are breaking xbox TOS
