### ISSUE TITLE
[Bug]: Gears of War 4 achievements does'nt works !

### ISSUE THREAD

**Issue by Benoit7338** [ItsLogic/Xbox-Achievement-Unlocker#251]
### What version of the Xbox Achievement Unlocker were you using (you can see this in the info page)?

2.7

### Tool Section

Achievements

### What is the bug?

Hello
A large BIG THANKS YOU for this magic tools !
Unfortunately, this does'nt work for Gears of War 4! Error Code :
Warning Partially Unsupported Game ! (Event achievements bug).

Thanks you for all your work ! (sorry for my bad english).

**Comment by VeryOriginalUsername2025** [comment]
it does work, but it's only 26/164 supported.
also you need your Event Token.

**Comment by Stivi85** [comment]
Could be great to e fixed. :)

**Comment by ItsLogic** [comment]
not a bug the game just isnt fully supported yet
