### ISSUE TITLE
problem when opening game achievement warning screen(see picture link)

### ISSUE THREAD

**Issue by Sebfrcan** [ItsLogic/Xbox-Achievement-Unlocker#26]
picture link below about the warning message i get, thanks waiting for a fix soon ! 

picture link: https://prnt.sc/Fe1Gw_y5eF5d
before i buy this to solve my problem: https://enzity.com/store/xam.29/releases

**Comment by HaZheRMx** [comment]
does not work for achievements in games from 2013 to 2017 approx
