### ISSUE TITLE
[Bug]: Dark Souls Remastered

### ISSUE THREAD

**Issue by xDzRICK** [ItsLogic/Xbox-Achievement-Unlocker#269]
### What version of the Xbox Achievement Unlocker were you using (you can see this in the info page)?

2.7

### Tool Section

Achievements

### What is the bug?

Warning: Unsupported game

How can I unlock event-based achievements? Please help me

**Comment by Xolara** [comment]
Not a bug. The warning is self-explanatory. Nobody released a script for the game to unlock achievements. 

Please refer to the list of supported event based games which can be found here: https://discord.com/channels/1013602813093359657/1233147226046599178

Keep in mind only PC and Android (to an extent) are currently supported.
