### ISSUE TITLE
Xbox 360 games say they have "no achievements"

### ISSUE THREAD

**Issue by mxvzs** [ItsLogic/Xbox-Achievement-Unlocker#27]
First of all, thanks a lot for your program.
But I'm facing a little issue. When I click on a 360 game, every one of them say they have no achievements, CoD: WaW for example (got a few buggy achievements that won't unlock).
Do you have some sort of a workaround for it ?
Thanks

**Comment by HaZheRMx** [comment]
because it doesn't work for Xbox 360 / Windows 8/ Games For Windows Live/ Windows Phone Games

**Comment by mxvzs** [comment]
> because it doesn't work for Xbox 360 / Windows 8/ Games For Windows Live/ Windows Phone Games

Oh ok, thanks for answering. Do you maybe know another program like this one but for Xbox 360 ?

**Comment by HaZheRMx** [comment]
yes: https://www.wemod.com/horizon

**Comment by mxvzs** [comment]
> yes: https://www.wemod.com/horizon

Thank you, I'll check it out

**Comment by ItsLogic** [comment]
360 games not supported and there are no plans to support them
