### ISSUE TITLE
I can't unlock the Need for Speed ​​(2015) achievements.

### ISSUE THREAD

**Issue by Karma401** [ItsLogic/Xbox-Achievement-Unlocker#28]
After I click to unlock the achievement, the achievement does not respond.

**Comment by hidekichanlee** [comment]
does not work for achievements in games from 2013 to 2017 approx

**Comment by HaZheRMx** [comment]
"Gold Plated" xD

**Comment by Karma401** [comment]
> does not work for achievements in games from 2013 to 2017 approx

Damn... is there any other way?

**Comment by Karma401** [comment]
> "Gold Plated" xD

I hate Prestige Challenge.;(
