### ISSUE TITLE
Can't start a game in DMC5

### ISSUE THREAD

**Issue by quim-clar** [ItsLogic/Xbox-Achievement-Unlocker#287]
### What version of the Xbox Achievement Unlocker were you using (you can see this in the info page)?

none

### Tool Section

Settings

### What is the bug?

When I execute dmc5, as its my first time, it says I have to create a game. So at the moment of creating it appears this message: "Error saving game". And its a loop, because it doesn't let me create a game so I cant play.

Any help please???

**Comment by VeryOriginalUsername2025** [comment]
this has absolutely nothing to do with the tool.
maybe google will help.
