### ISSUE TITLE
Interested in Unlocking a Few Glitched Achievements

### ISSUE THREAD

**Issue by attheshow2** [ItsLogic/Xbox-Achievement-Unlocker#3]
@ItsLogic Hey, I'm interested in unlocking a few glitched/unobtainable achievements in a game I've been working through. Is there any way we could discuss privately options on how to move forward with this? I might be able to offer you a gift card for your time if you're able to assist. The project is looking really good so far!

**Comment by ItsLogic** [comment]
I will be away from my main rig for the next week or so but if you have discord you can send me a friend request and we can talk there in the meantime
Draff#6900

(I will also close this issue after you add me as there isn't really anything to solve in it)
