### ISSUE TITLE
Nullable object must have a value

### ISSUE THREAD

**Issue by Vikos529** [ItsLogic/Xbox-Achievement-Unlocker#33]
tried repairing dotnet; reinstalling xau, doesn't work

**Comment by Vikos529** [comment]
![image](https://user-images.githubusercontent.com/105183894/225802032-59fa6340-6d12-4020-bc64-aceae28b5bf8.png)

**Comment by ItsLogic** [comment]
This isnt something I can solve. Sometimes the token just isnt complete and will cause unpredictableissues in the tool
