### ISSUE TITLE
App issues

### ISSUE THREAD

**Issue by rogueyoshi96** [ItsLogic/Xbox-Achievement-Unlocker#34]
it was working fine the last couple of weeks i dont know if its a server problem but it wont load my games anymore.
![226041939-7d0e47d9-2535-4a4b-adcd-3664d373d470](https://user-images.githubusercontent.com/128188039/226056778-18e6723c-5fe4-4310-8787-21b32bd180b9.png)

**Comment by rogueyoshi96** [comment]
.

**Comment by Vikos529** [comment]
same issue here

**Comment by rogueyoshi96** [comment]
I found out its not the program. Its xbox, they are having achievements issues so yeah.

**Comment by danielyoung669** [comment]
Ohhhhh this is why, thank you for the info, thinking they cleared my account :D. Realised I wasn't getting acheivements on my PC but they were going to my phone.

But yeah whole acheivement section is missing on the Xbox app (Mobile & PC).
