### ISSUE TITLE
Export Games in the same Format as Xbox-TitleIDs (Enhancement)

### ISSUE THREAD

**Issue by Jakesta13** [ItsLogic/Xbox-Achievement-Unlocker#35]
I was quickly playing around with the app and noticed the export format is flipped from the other project [Xbox-TitleIDs](https://github.com/ItsLogic/Xbox-TitleIDs), so I thought to mention the enhancement since people might want to use this method to add games to that project.

Would just need to flip these entries on the below line to apply the enhancement.
https://github.com/ItsLogic/Xbox-Achievement-Unlocker/blob/30018079cd89c7e73d80d740c2c5c8cc5685f61e/MainWindow.cs#L397

E.g
This project export:
`Game Title,ID`    
`Halo Infinite,2043073184`
Vs. [Xbox-TitleIDs](https://github.com/ItsLogic/Xbox-TitleIDs)
`ID, Game Title`    
`453673951,Guitar Hero Live
`
Edit: fixed examples

**Comment by Jakesta13** [comment]
I noticed I made a mistake on the issue, I'll edit this to reflect properly or close it if I'm wrong.

Not at my PC at the moment

**Comment by ItsLogic** [comment]
Honestly didnt even notice this. Ill change that line though thanks
