### ISSUE TITLE
[Game]: Astroneer

### ISSUE THREAD

**Issue by ghost** [ItsLogic/Xbox-Achievement-Unlocker#355]
### Confirmation

- [X] I have verified that this is not a duplicate request.

### Game Link

https://www.trueachievements.com/game/Astroneer/achievements

### Game Platform

Console and PC

### Additional Game Information

I would love to have this, as you cannot get achievements in a friend's world if that thing has already happened, so I've been locked out of a lot in the world I want to play in. Thanks!

**Comment by ethanwp28** [comment]
I have finished this, this game is apart of PR #360

**Comment by ghost** [comment]
> I have finished this, this game is apart of PR #360

Thank You!
