### ISSUE TITLE
[Bug]: Added own games, according to API. Unlock buttons remain nulled.

### ISSUE THREAD

**Issue by ghost** [ItsLogic/Xbox-Achievement-Unlocker#357]
### What version of the Xbox Achievement Unlocker were you using (you can see this in the info page)?

Patch1

### Tool Section

Achievements

### What is the bug?

Added games accordingly from steps in API, correctly.
Unlock button for achievements remains greyed out/nulled still, how are these buttons handled?
Cannot unlock for games/achievements added.

Care to add to documentation how these unlock buttons work? 
I'm a unity indie developer so have some background in c# just don't quite understand how the unlock button is handled after looking through the project and it's API.

An response in depth would be appreciated if could be resolved for this report,
Just an shame it's not disclosed in the API, adding games is there and achievements but not the actual handling of the button to unlock.

Thanks, I wanted to be able to come on board with this project in some way, even if its expanding the games library. 
for "play anywhere/xb/windows games"

Also, for example if I add a game following the API it still says the game is not supported at all, even after declaring the data in the data.json, achievements and the SupportTItleID field. and also the achievement handler data inside a T12345678910.json (Example).

**Comment by NextLVLHasH** [comment]
Eh what are you on about lol?
Also this isnt a bug, this is due to you not knowing how to read documentation behind how XAU actually works lol.
You need to learn about API's and read the XAU documentation Behind how to support a event based game.
You can view the documentation here:
[Doc/Events.md](https://github.com/Fumo-Unlockers/Xbox-Achievement-Unlocker/blob/Main/Doc/Events.md)

**Comment by ghost** [comment]
I added the games, exactly how the API explains to do so.
The unlock buttons remain nulled/greyed out, even on some titles which have been pre-loaded to the XAU.
Example, halo 5 forge has one achievement unlockable in it, when I add more achievement into data.json, with correct data they remain the same, unlockable.

If I have something wrong, which I may then I appreciate the input Fisko.

**Comment by NextLVLHasH** [comment]
did you add it under  "SupportedTitleIDs": [ in data

**Comment by ghost** [comment]
Correct, I followed the API.

**Comment by NextLVLHasH** [comment]
> Correct, I followed the API.

idk then
also ur not following a API lol

**Comment by ghost** [comment]
Visual studio has zero errors also, so I'm puzzled.
I entered everything as explained in the documentation.

**Comment by NextLVLHasH** [comment]
> Visual studio has zero errors also, so I'm puzzled. I entered everything as explained in the documentation.

bro vs wont show u a error in ur json formatting. you just need to format correctly.

**Comment by NextLVLHasH** [comment]
> Visual studio has zero errors also, so I'm puzzled. I entered everything as explained in the documentation.

also please change your name. your clearly not a actual dev lol. refering to Draffs docs as a API lol.

**Comment by ghost** [comment]
"SupportedTitleIDs": [
        974586226,
        1159891781
    ]

Developers are many things, just because I don't make app's on tamper with data under someone elses project does not mean I am not a developer, I make 2D Unity games... in a engine.
When I'm referring to the API I mean documentation, or whatever.
Everything is declared in the .json files, the Title ID one and the data.json but if you just want to throw negativity about then you're free to do so.

**Comment by NextLVLHasH** [comment]
> "SupportedTitleIDs": [ 974586226, 1159891781 ]
> 
> Developers are many things, just because I don't make app's on tamper with data under someone elses project does not mean I am not a developer, I make 2D Unity games... in a engine. When I'm referring to the API I mean documentation, or whatever. Everything is declared in the .json files, the Title ID one and the data.json but if you just want to throw negativity about then you're free to do so.

I will always throw my negativty around xD. thats just me, just upload your title id file & events to ur github and ill just look through them, also, no but a developer insists you work on actual code. just by being a unity dev who just uses the basic scripting ability doesnt count as being a developer, i dont class myself as a Dev, and i can make unity games, ive made software etc. point is if your actual job title doesnt state your a dev or you havent had 100's of users yes you might be a dev to yourself, but to the world you just aint, as you havent proved you are a real dev. 
As 90% of games use JSON as a DB for their ingame stuff like guns weapons etc, if you cant understand basic Json data, that shows you just use scripting.

**Comment by ItsLogic** [comment]
bro can you stop hating :skull:
