### ISSUE TITLE
Why Xbox360 Games not working (No-Achievement)

### ISSUE THREAD

**Issue by FarGoneChris** [ItsLogic/Xbox-Achievement-Unlocker#36]
I love the program. I have used it but no Xbox360 games. I know you can't make everything work but can you add it sometime soon. also a site was tagged but you have to pay for the achievement unlocker

**Comment by sunk1ll3r** [comment]
This isn't meant for 360 and he's already said he's not adding. 360 achievements are completely different from xbox one and there's plenty of 360 unlockers already. google it.

**Comment by ItsLogic** [comment]
360 games not supported and there are no plans to support them.
