### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by yopJJ** [ItsLogic/Xbox-Achievement-Unlocker#37]
## Error

**An unhandled exception has occurred**. This is for **all versions** and when I was using it **yesterday it was completely fine** and working! But now it has left me in tears :sob:, please get back quickly, @ItsLogic!

  
![image](https://user-images.githubusercontent.com/65462136/229357857-e31071ff-87aa-4f92-884b-51d502511045.png)

**Comment by M4u87** [comment]
Same problem today

**Comment by ItsLogic** [comment]
It just happens sometimes and there is nothing I can do about it because the xauth token isn't always properly in memory.
If you restart the xbox app service enough times it will eventually work
