### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by ATrejo98** [ItsLogic/Xbox-Achievement-Unlocker#38]

**Comment by ATrejo98** [comment]
![image](https://user-images.githubusercontent.com/119873227/232384042-7c1868a2-fcb0-410a-9820-65e64b7222d1.png)


Why?

**Comment by Exohayvan** [comment]
https://github.com/ItsLogic/Xbox-Achievement-Unlocker/issues/32#issuecomment-1464689417
