### ISSUE TITLE
Display in profile Xbox

### ISSUE THREAD

**Issue by Darkrogua** [ItsLogic/Xbox-Achievement-Unlocker#40]
Hello everyone, I recently used your program to unlock several games. Some of them are displayed correctly in the profile with 1000/1000, while others, such as RedFall and Daymare 1998, show less than 1000 points, even though all achievements are unlocked. Is this a problem on Microsoft's end? Also, what do achievements with events mean?" translates to:

"Hello everyone, I have recently used your program to unlock several games. Some of them are displayed correctly in the profile with 1000/1000, while others, such as RedFall and Daymare 1998, show less than 1000 points, even though all achievements are unlocked. Is this a problem on Microsoft's end? Also, what do achievements with events mean? **Your application is great!**

**Comment by AlexandreCA** [comment]
I have exactly the same problem. Any idea?

**Comment by ItsLogic** [comment]
This is a microsoft issue. When you unlock a bunch of achievements at once it doesn't update everywhere at once for some reason. Im assuming its some sort of cache issue. After a few days it will return to normal and the display will be correct everywhere

**Comment by AlexandreCA** [comment]
I see.. That's good to know. I will look at this closely in a few days to see if everything is back to normal.
