### ISSUE TITLE
Issue with Xbox 360 Games

### ISSUE THREAD

**Issue by Naser115** [ItsLogic/Xbox-Achievement-Unlocker#43]
It doesn't seem to detect Xbox 360 games, it labels them as games with no achievements. Is there a work around?

**Comment by sunk1ll3r** [comment]
Yeah. It's called google and one of the 360 achievement unlockers that have been around for over a decade. Also called look through other posts here and see this question already answered.

**Comment by ItsLogic** [comment]
There are no plans to add xbox 360 game support for unlocking.
