### ISSUE TITLE
[Feature-Request]: stat changer 

### ISSUE THREAD

**Issue by OpenSorcererBLNK** [ItsLogic/Xbox-Achievement-Unlocker#49]
### Tool Section

Unlocker

### What feature are you requesting?

Hey Logic! Just seeing how much of a priority of getting the stat changer to work. Correctly? I LOVE this feature and would be so happy if it was working. Thanks so much!

**Comment by ItsLogic** [comment]
Getting the stats editor to work "properly" will require me to figure out event based things. As of right now it only works on title based stats but it seems the majority of games use event based stats. There isnt a reliable way to tell if a game is using title or event based stats as its not connected to achivements so I cant provide a message saying if a game will work or not before the user tries.
It should come shortly after event based achivements (whenever that may be)

**Comment by OpenSorcererBLNK** [comment]
I’ve used it on games (non event based) and it’s says “successful” but doesn’t change on my stats in game. Am I doing something wrong? Thanks for the quick reply :)

**Comment by ItsLogic** [comment]
No the "successful" refers to the request itself. Xbox actually saving the stat isn't something thats returned from the server

**Comment by ItsLogic** [comment]
closing this as it will now be covered within the completion of #62
