### ISSUE TITLE
XAUTH will not be found if you open it again

### ISSUE THREAD

**Issue by thevenomsnake** [ItsLogic/Xbox-Achievement-Unlocker#5]
When I exit the unlocker and open it again, XAUTH will not be found and I need to restart my computer to fix it.

**Comment by ItsLogic** [comment]
what application?
The unlocker or the xbox app?

**Comment by thevenomsnake** [comment]
yes :)

**Comment by mrsloth4994** [comment]
Just opened the unlocker and clicked grab xauth and got an error saying Something with the xauth scan did a fucky wucky. It has been working perfectly the last week but today I get this error?

**Comment by HaZheRMx** [comment]
> Just opened the unlocker and clicked grab xauth and got an error saying Something with the xauth scan did a fucky wucky. It has been working perfectly the last week but today I get this error?

It's something from Windows or some update... because on my other Laptop it works

**Comment by mrsloth4994** [comment]
> > Just opened the unlocker and clicked grab xauth and got an error saying Something with the xauth scan did a fucky wucky. It has been working perfectly the last week but today I get this error?
> 
> It's something from Windows or some update... because on my other Laptop it works

Hmm. Well I'm not sure if that's correct as nothing has changed, no update has been installed or changed

**Comment by mrsloth4994** [comment]
Figured it out. Normally I open to tool then grab xauth straight after but if I wait around 20-30 seconds then press grab xauth it works

**Comment by System32-0** [comment]
> Figured it out. Normally I open to tool then grab xauth straight after but if I wait around 20-30 seconds then press grab xauth it works

The way I found it, is 
> open unlocker tool
> open xbox app
> grab all

Sometimes if you close the unlocker and start it fairly quickly after, it will throw an error.
