### ISSUE TITLE
[Bug]: Doesn't Show Any Achievements for Xbox 360 Games

### ISSUE THREAD

**Issue by MechanicManTyler** [ItsLogic/Xbox-Achievement-Unlocker#51]
### What version of the app were you running?

1.8

### Winver

Win11

### Have I checked if the bug was reported?

No

### What is the bug?

When i try any xbox 360 games associated with my gametag that i have played, it shows a message saying the game has no achievements

**Comment by HellAleX92** [comment]
it's not a bug, it's a feature.
360 games are not featured.

a quick search in the closed issues would have helped.
https://github.com/ItsLogic/Xbox-Achievement-Unlocker/issues/43
