### ISSUE TITLE
Game Title ID with all avaible Xbox one games[Feature-Request]: 

### ISSUE THREAD

**Issue by rogueyoshi96** [ItsLogic/Xbox-Achievement-Unlocker#52]
### Tool Section

Unlocker

### What feature are you requesting?

Is it possible to make a feature so we can have all title id's for Xbox games available to us from the get go? ATM I use a website called Gameclips.io and I look up the name and take the id from there and use it to spoof games that I can't purchase due to being de-listed or other reasons.

**Comment by VelocityRektz** [comment]
Yes, it is currently a feature being worked on.

**Comment by ItsLogic** [comment]
closing this as there is now game search functionality in 2.1.0
