### ISSUE TITLE
Build solution not working

### ISSUE THREAD

**Issue by igorissen** [ItsLogic/Xbox-Achievement-Unlocker#54]
Hello,

I'm trying to build the project and I'm getting an error during the build saying that the dependency Memory is not found or does not exist.

![2023-08-12 09_52_24-Window](https://github.com/ItsLogic/Xbox-Achievement-Unlocker/assets/6919604/e84bd8c1-4b16-4547-814b-a1131478e258)

Do you have an idea why ?

Thanks

**Comment by ItsLogic** [comment]
You seem to be missing the memory.dll nuget package.

**Comment by igorissen** [comment]
Strange because the Nuget package manager saying that it is installed.

![2023-08-12 12_15_36-Window](https://github.com/ItsLogic/Xbox-Achievement-Unlocker/assets/6919604/168c0e63-80d8-4752-b595-9979fab140f1)

**Comment by igorissen** [comment]
I found a solution with this post : https://learn.microsoft.com/en-us/nuget/consume-packages/package-restore-troubleshooting
Now it's working.

Thanks.
