### ISSUE TITLE
[Feature-Request]: Filter/Search in the Achievement List window & Hide/Show unlocked achievements

### ISSUE THREAD

**Issue by 7s3** [ItsLogic/Xbox-Achievement-Unlocker#55]
### Tool Section

Unlocker

### What feature are you requesting?

I think it would be beneficial to have (2) new features:

- The ability to search for achievement names in the Achievement List window (and filter out non-matching results)
- Checkbox to hide/show already unlocked achievements so the window is less cluttered

**Comment by ItsLogic** [comment]
this is now complete in #56

**Comment by 7s3** [comment]
Any plans to add this back into the app after the 2.0 update?

**Comment by ItsLogic** [comment]
> Any plans to add this back into the app after the 2.0 update?

Yeah it should be in the next update. ~~I just forgot to add it twice~~

**Comment by bikram-agarwal** [comment]
Hi. I wanted to request a new feature - `toggle to hide/show already unlocked achievements`.

I searched for it in the issues and found this issue; which says this feature will be added back in the next update. I'm guessing you might've forgotten it for the third time. 😆 Will this be added in any near future update?
