### ISSUE TITLE
[Bug]: Possible to accidentally unlock UNCHECKED achievements

### ISSUE THREAD

**Issue by 7s3** [ItsLogic/Xbox-Achievement-Unlocker#57]
### What version of the app were you running?

1.8.2

### Winver

Win10

### Have I checked if the bug was reported?

Yes

### What is the bug?

If you have an achievement checked, and then refresh the list, change the sorting (Unlockable/Unlocked) or change the search filter, the previously checked achievement will then **appear** unchecked.

The next time you press the unlock button, it will unlock this achievement that visually is showing as unchecked. 

Probably is best to clear all checks in the "backend" whenever there's a refresh or change in the filters (other than sorting by ID#, A-Z, etc.)

**Comment by ItsLogic** [comment]
Man this latest update caused a lot of bugs lmao.
This is an easy fix though I will push an update tomorrow with a hotfix
