### ISSUE TITLE
Can you get banned for using this?

### ISSUE THREAD

**Issue by th0masGR** [ItsLogic/Xbox-Achievement-Unlocker#59]
Can you get banned for using this?

**Comment by ItsLogic** [comment]
yes

**Comment by th0masGR** [comment]
so, how you use it?

**Comment by VeryOriginalUsername2025** [comment]
> so, how you use it?

asking this question -> just don't use it at all.

**Comment by mickygamer44** [comment]
How Many activement you can do each day ? 10-12 achèvement with gamespoofer is allright ?
