### ISSUE TITLE
Not Launching

### ISSUE THREAD

**Issue by jayjoke12** [ItsLogic/Xbox-Achievement-Unlocker#61]
Even after installing dotnet7 and running xboxApp it still doesn't work!

**Comment by ItsLogic** [comment]
The new version of memory.dll doesnt play nicely with windows defender (and windows defender doesnt notify you that its blocked)
Check your defender protection history to see if memory.dll is there and allow it 
![image](https://github.com/ItsLogic/Xbox-Achievement-Unlocker/assets/38233332/81ee1bdd-d0a8-4c00-8a91-bac05ae877b7)

**Comment by lvzys** [comment]
I've done what you said and it still doesn't work.

**Comment by ItsLogic** [comment]
closing as this should no longer be an issue as of 2.3
