### ISSUE TITLE
Perfect Unlocker but still no event based achievements or 360 achievements

### ISSUE THREAD

**Issue by WH1T3S1LV3R** [ItsLogic/Xbox-Achievement-Unlocker#71]
I really enjoy your app everything is perfect only issue I have is that it doesn't support 360 achievements or event based (cloud based)  achievements. I hope it gets added. If not I'll still use it you all did a great job <3

**Comment by hidekichanlee** [comment]
For XBOX 360 he has already said that he will not implement it, there is already a paid program for that, it is called HORIZON and the event based achievement he is still working on but the ETA for 2030 in the official topic.

**Comment by hidekichanlee** [comment]
> I really enjoy your app everything is perfect only issue I have is that it doesn't support 360 achievements or event based (cloud based) achievements. I hope it gets added. If not I'll still use it you all did a great job <3


For XBOX 360 he has already said that he will not implement it, there is already a paid program for that, it is called HORIZON and the event based achievement he is still working on but the ETA is for 2030 in the official topic.

**Comment by asutermo** [comment]
people need to read the README lmao

**Comment by ItsLogic** [comment]
event based games are now supported
there are no plans for 360
