### ISSUE TITLE
Latest version just crashes when I filter games? 

### ISSUE THREAD

**Issue by SilverWhale44** [ItsLogic/Xbox-Achievement-Unlocker#76]
Latest version just crashes when I filter games? It doesnt matter if I select PC or Xbox Series

**Comment by ItsLogic** [comment]
This is sub optimal. Ill have a look into it tomorrow to see if I can reproduce

**Comment by ItsLogic** [comment]
closing this as filters should now be fixed in latest version. Reopen if the bug still happens
