### ISSUE TITLE
Version 2.3.1 not logging in.

### ISSUE THREAD

**Issue by sean-broccoli** [ItsLogic/Xbox-Achievement-Unlocker#80]
Updated the app from 2.2 to 3.2.1. App attaches but doesnt log in. Updated Xbox app. Still no luck. Version 2.2 still logs in fine.

**Comment by hidekichanlee** [comment]
Mine logs in perfectly, after reading this I tried it and it logged in 100%

**Comment by sean-broccoli** [comment]
![2024-04-18 19_32_27-Version 2 3 1 not logging in  · Issue #80 · ItsLogic_Xbox-Achievement-Unlocker -](https://github.com/ItsLogic/Xbox-Achievement-Unlocker/assets/167483331/93d70776-2a34-44b1-b2e8-9f18531919f3)

**Comment by hidekichanlee** [comment]
Sorry, but it's not a problem with the program, it's something on your computer.
![Sem título](https://github.com/ItsLogic/Xbox-Achievement-Unlocker/assets/56121293/130cdd87-5cbd-4f55-8e3d-5faf02843e06)

**Comment by sean-broccoli** [comment]
I understand that but the whole point is to get help to figure out what the issue is...... I can launch Version 2.2 and log in with no issues. There is no reason why one should work and not the other.

**Comment by hidekichanlee** [comment]
I think the problem is with the Windows Xbox Application, if you open it it will probably be logged out, something similar happened to me a while ago, but it corrected itself.

**Comment by Xolara** [comment]
Version 3.2.1, Mind sending me the source/.exe for it? I'd like to know what XAU has in the future. Thanks!

**Comment by VeryOriginalUsername2025** [comment]
it does support xbox 720, the successor of the 360. I know it because Bill Gates is my dad!

@sean-broccoli just be patient. it does need a little bit to log in. for fuck sake, wait a minute and you're good.

**Comment by ItsLogic** [comment]
> I understand that but the whole point is to get help to figure out what the issue is...... I can launch Version 2.2 and log in with no issues. There is no reason why one should work and not the other.

does opening it with admin help?
