### ISSUE TITLE
[Bug]: Not grabbing my XAuth token

### ISSUE THREAD

**Issue by BlueBoopYT** [ItsLogic/Xbox-Achievement-Unlocker#82]
### What version of the Xbox Achievement Unlocker were you using (you can see this in the settings page)?

Latest

### Tool Section

Other- Please put more information in the box below

### What is the bug?

So I open the XAU.exe it opens Xbox app it attaches but it never gets my XAUTH token.

**Comment by ItsLogic** [comment]
if you run the tool as admin does it find it?

**Comment by BlueBoopYT** [comment]
no it dose not

**Comment by BlueBoopYT** [comment]
i will send video

**Comment by BlueBoopYT** [comment]
video link


https://github.com/ItsLogic/Xbox-Achievement-Unlocker/assets/167948714/a8e66412-24a4-4105-ba3f-e0248e481f45

or

https://youtu.be/l5QNo3zgZRg?si=9dI7iGFI6IaSkbE1

**Comment by ItsLogic** [comment]
Interesting. This obviously shouldn't happen but I'm not sure why it does.
It could be related to the insider version of the xbox app? Ill try to look into it. In the meantime can you try the non insider version of the xbox app
