### ISSUE TITLE
game time adder or adding capabilities 

### ISSUE THREAD

**Issue by Spffin** [ItsLogic/Xbox-Achievement-Unlocker#9]

**Comment by Spffin** [comment]
also thanks for the work

**Comment by ItsLogic** [comment]
This is pretty interesting. I had saw these but didnt actually know it "added" the game to your account
Also yeah I have a discord its currently Draff#6900

**Comment by Spffin** [comment]
ill add you to give you my feed back ❤

**Comment by Spffin** [comment]
and yes "spoofing" add the game

**Comment by ItsLogic** [comment]
I think this would be a good feature to add though. Would be super easy to implement and it partially falls within the scope of the app

**Comment by XbotZZ** [comment]
Just a message to thank you for your work @ItsLogic 
Work perfectly and i manage to get some buggy achievements

**Comment by HaZheRMx** [comment]
> it is possible to get banned ?

if you are going to unlock Discontinued achievements... of course you will be banned, like all those who unlocked GEARS POP and the game stopped working on April 26, 2021

**Comment by DarkUnicycle** [comment]
Just writing to thank you for your hard work. Excited to see what you add to future releases!

**Comment by ItsLogic** [comment]
Feature added in [f7fae2c](https://github.com/ItsLogic/Xbox-Achievement-Unlocker/commit/f7fae2c6fd5ceafcdb3ed8230169a863d3710604)
